### ISSUE TITLE
compare taxonRank info with info from nameparser function

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/daisie-checklist#11]
Information about the taxon rank can be provided in two ways:
1. By using the information in `subtaxon_rank` in the taxon core. This relates to the original information in DAISIE. This information should thus only apply for subtaxa
2. By using the information in `rankmarker`, provided by the GBIF nameparser 

It would be interesting to see the differences between the returns of the GBIF nameparser and the content of the `subtaxon_rank` field

**Comment by LienReyserhove** [comment]
This is the result of the comparison:
(more interpretation, see next comment)


|nameparser_rankmarker  |taxon_subtaxon_rank | records|
|:-----------|:----------------|-------:|
|sp.         |                 |   10774|
|infrasp.    |subsp.           |     518|
|sp.         |hyb.             |     329|
|infrasp.    |var.             |     141|
|infrasp.    |                 |     136|
|NA          |hyb.             |      54|
|NA          |                 |      30|
|morph       |                 |      23|
|sp.         |var.             |      18|
|NA          |agg.             |      14|
|morph       |subsp.           |      11|
|cv.         |hyb.             |      10|
|sp.         |agg.             |       6|
|pv.         |                 |       5|
|sp.         |                 |       5|
|sp.         |subsp.           |       5|
|cv.         |                 |       4|
|infrasp.    |f. sp.           |       4|
|var.        |var.             |       4|
|infrasp.    |x                |       3|
|strain      |subsp.           |       3|
|var.        |subsp.           |       3|
|infrasp.    |f.               |       2|
|infrasubsp. |                 |       2|
|var.        |                 |       2|
|cv.         |subsp.           |       1|
|cv.         |var.             |       1|
|f.          |var.             |       1|
|infrasp.    |agg.             |       1|
|infrasp.    |Crous            |       1|
|infrasp.    |subspecies       |       1|
|infrasp.    |var              |       1|
|infrasubsp. |hyb.             |       1|
|morph       |var.             |       1|
|sp.         |Cytosporina sp.  |       1|
|sp.         |f. sp.           |       1|
|sp.         |sp.              |       1|
|subf.       |var.             |       1|
|subsp.      |                 |       1|
|subvar.     |subsp.           |       1|
|NA          |subsp.           |       1|

**Comment by LienReyserhove** [comment]
I noticed the following: 
- the large bulk of taxa (10774 out 12122): `nameparser_rankmarker = species` , while `taxon_subtaxon_rank = empty` (which is quite logic). 
- For about 500 taxa:  `nameparser_rankmarker = infraspecies`, while `taxon_subtaxon_rank = subspecies`
- For 329 taxa: `nameparser_rankmarker = species`, while `taxon_subtaxon_rank = hybrid`
We do not use `hybrid` as a taxonRank anymore, so I suspect the information provided by the nameparser is more correct in this case.

SO: for about 11000 species, the information provided by the rankmarker should be considered as OK (and even better). So just use the taxon rank information provided by GBIF ?

@peterdesmet , @DavidRoy, @qgroom ?

**Comment by DavidRoy** [comment]
Yes, I think so.  With a project more than 10 years old, we cannot go back and investigate the inevitable errors in the DAISIE database.  I think we (you!) do the best job of mapping that can be done in the time available.  Thanks for all your efforts!

**Comment by LienReyserhove** [comment]
Ok, thanks for the response!
Closing the issue.

**Comment by peterdesmet** [comment]
GBIF rankmarker will indeed provide cleaner information than `taxon_subtaxon_rank`, even if there might be some loss of information.
