### ISSUE TITLE
scientificNameAuthorship

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/daisie-checklist#14]
The `input_taxon` file now contains two fields refering to an authorship:

sp_genus | sp_species | sp_authority | sp_subtaxon | sp_subtaxon_authority |
--- | --- | --- | --- | ---
Daucus | guttatus | Sibth. & Sm. | zahariadii | Heywood

I now integrated this information in the field `scientificName`:
>Daucus guttatus Sibth. & Sm. zahariadii Heywood

This is a GBIF accepted taxon (tested is using the [GBIF look up tool](https://www.gbif.org/tools/species-lookup)). But what is the `scientificNameAuthorship` here?
@qgroom

**Comment by qgroom** [comment]
The scientificNameAuthorship would be Heywood in this case
