### ISSUE TITLE
sources in taxon core

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/daisie-checklist#20]
The taxon core contains 2 fields reserved for sources: `bibliographicCitation` and `references` (see [here](http://rs.gbif.org/core/dwc_taxon_2015-04-24.xml)). 

However, the only valid use of the term `bibliographicCitation` is to indicate the source of the taxon record (a field “source” is not available in the taxon core, in contrast with distribution extension). `refernces` should be a URL to that record on a public website. However, some sources included in raw_taxon are none of both categories, e.g.:

> Carpaneto G (1990) The Indian Grey Mangoose (Herpestes edwardsii) in the Circeo national Park:a case of incidental introduction. Mustelid and Viverrid Conservation, 2:10

Some are:

> Davis PH et al (eds) (1965) Flora of Turkey and the East Aegean Islands, vol 1. University Press, Edinburgh

I'm tempted to exclude this information, but of course, then we lose information from the original dataset.
suggestions? @peterdesmet @DavidRoy

**Comment by peterdesmet** [comment]
At a database level, what is this info related to? The taxon? If so and you want to include it, including it in `taxonRemarks` _as is_ is probably the best option.

**Comment by LienReyserhove** [comment]
yes, related to the taxon information at the database level. `taxonRemarks` could be an option, but now there's information about the ecofunctional group in this field. Could leave that information out, and add it to the description extension...

**Comment by LienReyserhove** [comment]
However, this will make the description a real dump-field...

**Comment by peterdesmet** [comment]
With “ecofunctional group” as type, it seems fine to add that to description. The info you plan to add to taxonRemarks seems more like a mixed bag.

**Comment by LienReyserhove** [comment]
Ok, I will extract the information and add it to the description extension then.
