### ISSUE TITLE
Different number of taxa in database <-> book

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/daisie-checklist#26]
In the introduction of the DAISIE handbook, it is stated that the database includes 10857 species. However, in the taxon core, I count 12115 taxa (most of those are species). 
@DavidRoy any explanations for this discrepancy?

**Comment by LienReyserhove** [comment]
Issue solved after going through the handbook chapter 10:

>Also, as the database is being updated, the species numbers presented in this book will deviate from the future state of the database.

**Comment by DavidRoy** [comment]
Yes, there were updates after the book (particularly for plant)
