### ISSUE TITLE
How to publish DAISIE

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/daisie-checklist#3]
The background information of DAISIE is published in the book "Handbook of Alien Species in Europe". In this book, each taxonomical group is published as a different chapter, with its own authorship:
1. Alien fungi
2. Alien Bryophtytes and Lichens
3. Alien vascular plants 
5. Alien Terrestrial invertebrates
6. Alien invertebrates and fish
7. Alien marine biota
8. Alien birds, amphians and reptiles
9. Alien mammals

For the publication of DAISIE, I got two options:

1. Publish a subset of DAISIE for each taxonomical group 
**Advantage**: it would be easier for researchers to scan for their specific species group
**Advantage**: it would greatly reduce the list of authors (only max. of 6 authors)
**Advantage**: each checklist would be published with its own metadata (from the book)
**Advantage**: each checklist could be link under the project information "DAISIE" (as we do in TrIAS)
**Disadvantage**: This implies that 9 (!) DAISIE checklists will be published
**Disadvantage**: much more work writing the metadata 
 
2. Publish the checklist as one large checklist on GBIF. 
**Advantage**: evident, only one DAISE checklist on GBIF, which is our usual approach. Much easier to import the data and filter on the data as a whole
**Disadvantage**: a very large group of authors.

I discussed this with @DavidRoy and for him it's not an option to only include the first author of each taxonomical group, and to include the rest in the metadata (if we would publish the dataset as a whole)

I prefer option 2, and just keep the checklist as a whole, which is what we always try to do. Of course I understand the advantages of splitting up the checklist. 

@qgroom, @peterdesmet , @timadriaens @SoVDH ?

**Comment by qgroom** [comment]
The best way IMHO is to cheat the system like we do for the herbarium ([](https://www.gbif.org/dataset/b740eaa0-0679-41dc-acb7-990d562dfa37)).
That is, create an organization as an author. The metadata can then encourage users to cite specific people and previous publications where they exist.
Quentin

**Comment by SoVDH** [comment]
In terms of visibility, having one big dataset is better than several small ones.
Regarding DAISIE, I'm not sure the trick which consists in highlighting organisations will solve your problem : in this kind of projects, there are almost as many institutions as individuals involved.

**Comment by qgroom** [comment]
Yes, what I meant was to make DAISIE the author.

**Comment by peterdesmet** [comment]
I would **definitely** publish as one dataset!

Regarding authors, I’m fine with having a loooot of authors. I generally like that better than having org as author.

**Comment by LienReyserhove** [comment]
Ok, thanks to confirm, I will publish the checklist as one dataset. Thanks for the input. 
Closing this issue
