### ISSUE TITLE
metadata decisions required

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/daisie-checklist#6]
For the following metadata fields, we need to decide the content. 
@DavidRoy 
@peterdesmet 

For source datasets, we tend to use the following rules: 
> publisher = institutionCode = rightsHolder = the organization that had or was granted the permission to publish the data under the license it has. We make this closest to the source organization as possible

- license: CC-BY
- publisher: Centre for Ecology and Hydrology
- institutionCode = CEH
- rightsHolder: Centre for Ecology and Hydrology
- datasetName= Inventory of alien species in Europe (DAISIE)

We could publish the checklist using the INBO IPT, but then we need to register CEH...

**Comment by peterdesmet** [comment]
Sounds good to me. I assume “Centre for Ecology and Hydrology” is the maintainer of the DAISIE database?

Would register org with GBIF (or is that already done?) and publish through INBO IPT.

**Comment by DavidRoy** [comment]
CEH is implementing a GBIF IPT so I would prefer it to go through there if that's ok

**Comment by LienReyserhove** [comment]
That is fine for me, when do you think this IPT will be available?

**Comment by DavidRoy** [comment]
Will get back to you on timing.  Could we test via the INBO IPT and then switch over when we go properly live?

**Comment by peterdesmet** [comment]
1. We generally prepare the files and write the metadata outside of the IPT, so no need to _test_ via the INBO IPT.
2. If by the time we are ready to publish there is no CEH IPT yet, I propose to publish via INBO IPT
3. We can always move that dataset to the CEH IPT later

For setting up a production IPT, it is important to have a stable URL (without port information included).

**Comment by LienReyserhove** [comment]
If we can indeed easily move the dataset o the CEH IPT later (no experience with that), I agree with publishing first via INBO IPT.
